### ISSUE TITLE
Consider using webroot instead of standalone

### ISSUE THREAD

**Issue by christophersansone** [henridwyer/docker-letsencrypt-cron#1]
I ran into a couple issues trying to get this configured with my nginx setup.
1.  Having letsencrypt listen on port 80 could cause a collision with nginx depending on the Docker network configuration.  It works fine in the default bridge mode, but it will fail in host mode and could be problematic in an overlay network.
2.  Having nginx proxy it upstream can be problematic.  If for instance you are simply generating a certificate by running `docker-compose run letsencrypt /run_letsencrypt.sh`, nginx will not link to that container.

I got it all working by changing /run_letsencrypt.sh to use the webroot configuration instead.  The `letsencrypt` command is now simply this:

```
letsencrypt --webroot --agree-tos --renew-by-default\
  --server https://acme-v01.api.letsencrypt.org/directory\
  --webroot-path /webroot --email $EMAIL -d $d certonly
```

I then added a volume to docker-compose.yml to link the nginx root path into this container:

```
letsencrypt:
  ...
  volumes:
    ...
    - /var/www/html:/webroot
```

This method seems more resistant to issues involving container communication, and it eliminates the need to edit the nginx (or apache) config files.  The only drawback is that it requires the web root path to be external to the nginx container (either on the host filesystem or as a separate volume), so that it can be available to both containers.  This seems fairly commonplace, and it is simple to do otherwise.

Would you be interested in considering this change?  If so I'd be happy to submit a PR.

**Comment by christophersansone** [comment]
Quick follow-up.  I ran into a situation today where I was installing it on a server that did not have a web server, so standalone mode was ideal.

I'm thinking that supporting both the standalone and webroot options would be ideal.  If the environment variable `WEBROOT_PATH` is specified, it would assume the webroot option and use the value as the webroot path for letsecrypt.  If `STANDALONE_HTTP_PORT` is specified, it would run letsencrypt in standalone mode on a specific port (which would provide options to those running non-bridged networking in Docker).  If neither are specified, it will run in standalone mode over port 80.

Again, happy to submit a PR if you're interested.  Thanks!

**Comment by henridwyer** [comment]
@christophersansone Thanks for the feedback. I added a webroot variable that would allow one to specify the webroot path. Perhaps you're right and it's useful to add a variable to specify the standalone port.

Does that address your usage and requirements?

I'm happy to merge a PR if you want to add the standalone http port
